apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dinnu814/webapps:nginx-app_v3
        ports:
        - port: 80
          targetPort: 80
          nodePort: 8099          
